# Generated by Django 6.0 on 2026-01-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_producto', models.ImageField(upload_to='media/')),
                ('nombre_producto', models.CharField(max_length=120)),
                ('descripcion_producto', models.TextField()),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('comida_rapida', 'Comida rápida'), ('bebida', 'Bebida'), ('combo', 'Combo'), ('postre', 'Postre')], max_length=50)),
                ('disponible', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creada'],
            },
        ),
    ]
