# Generated by Django 6.0 on 2026-01-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='img_producto',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
