# Generated by Django 5.2.4 on 2026-01-03 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_alter_productos_img_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_pedido', models.DateField(blank=True, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.TextField(blank=True)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], default='efectivo', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendas.productos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tiendas.venta')),
            ],
        ),
    ]
