# Generated by Django 6.0 on 2026-01-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0003_venta_alter_productos_id_detalleventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
