# Generated by Django 6.0 on 2026-01-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0004_alter_detalleventa_id_alter_productos_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fecha_pedido',
        ),
    ]
